// <auto-generated />
using System;
using BovinosApi;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BovinosApi.Migrations
{
    [DbContext(typeof(BoiDbContext))]
    [Migration("20251021022826_InitialCreateVacas")]
    partial class InitialCreateVacas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("BovinosApi.Boi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("DataNascimento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<string>("Origem")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Peso")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Raca")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.Property<string>("observacoes")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Bois");
                });
#pragma warning restore 612, 618
        }
    }
}
